export const state = {
  prefectures: [],
  elements: null,
  manifest: null,
  selectedElementKey: "",
  stationConfigCache: new Map(),
  tableCache: new Map(),
  pointChunkCache: new Map(),
  pointDailyCache: new Map(),
  latestTimeCache: {
    iso: "",
    fetchedAt: 0,
  },
  latestMapCache: {
    iso: "",
    data: null,
    fetchedAt: 0,
  },
  debug: {
    selectedRegion: "",
    selectedPrefKey: "",
    selectedPrefName: "",
    selectedMonth: "",
    selectedElementKey: "",
    selectedElementLabel: "",
    stationsPath: "",
    tablePath: "",
    latestObservationTime: "",
    pointFetchCount: 0,
    tableRowCount: 0,
    summaryItemCount: 0,
    liveSupported: "",
    liveError: "",
  },
};
